version: '3.3'

services:
  mongodb:
    image: mongo:3.6
    ports:
      - 27017:27017
  redis:
    image: redis
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - 15672:15672
      - 5672:5672
