volumes:
  minio-data:

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        /bin/sh -c "
        set -x;
        mc alias set myminio http://minio:9000 minioadmin minioadmin;
        mc mb myminio/bucket;
        "
