version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2022-05-26T05-48-41Z
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin